name: Initial setup action
description: Reusable action to setup node and install packages with yarn

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v6
      with:
        node-version: 22
        cache: 'yarn'

    - name: Install dependencies
      run: |
        yarn install --immutable
      shell: bash
