import { CosmosGasDenom, CosmosNetworks, Networks } from '../enums';
import { CosmosChainConfig } from '../interfaces';

export const cosmosChainConfig: {
  [x in CosmosNetworks]: CosmosChainConfig;
} = {
  [Networks.Akash]: {
    network: Networks.Akash,
    chainId: 'akashnet-2',
    name: 'Akash',
    denom: CosmosGasDenom.AKT,
    minimalDenom: CosmosGasDenom.uakt,
    decimals: 6,
    bech32Prefix: 'akash',
    coinGeckoId: 'akash-network',
  },
  [Networks.Cosmos]: {
    network: Networks.Cosmos,
    chainId: 'cosmoshub-4',
    name: 'Cosmos',
    denom: CosmosGasDenom.ATOM,
    minimalDenom: CosmosGasDenom.uatom,
    decimals: 6,
    bech32Prefix: 'cosmos',
    coinGeckoId: 'cosmos',
  },
  [Networks.Kava]: {
    network: Networks.Kava,
    chainId: 'kava-9',
    name: 'Kava',
    denom: CosmosGasDenom.KAVA,
    minimalDenom: CosmosGasDenom.ukava,
    decimals: 6,
    bech32Prefix: 'kava',
    coinGeckoId: 'kava',
  },
  [Networks.Osmosis]: {
    network: Networks.Osmosis,
    chainId: 'osmosis-1',
    name: 'Osmosis',
    denom: CosmosGasDenom.OSMO,
    minimalDenom: CosmosGasDenom.uosmo,
    decimals: 6,
    bech32Prefix: 'osmo',
    coinGeckoId: 'osmosis',
  },
  [Networks.Juno]: {
    network: Networks.Juno,
    chainId: 'juno-1',
    name: 'Juno',
    denom: CosmosGasDenom.JUNO,
    minimalDenom: CosmosGasDenom.ujuno,
    decimals: 6,
    bech32Prefix: 'juno',
    coinGeckoId: 'juno-network',
  },
  [Networks.Stargaze]: {
    network: Networks.Stargaze,
    chainId: 'stargaze-1',
    name: 'Stargaze',
    denom: CosmosGasDenom.STARS,
    minimalDenom: CosmosGasDenom.ustars,
    decimals: 6,
    bech32Prefix: 'stars',
    coinGeckoId: 'stargaze',
  },
  [Networks.Persistence]: {
    network: Networks.Persistence,
    chainId: 'core-1',
    name: 'Persistence',
    denom: CosmosGasDenom.XPRT,
    minimalDenom: CosmosGasDenom.uxprt,
    decimals: 6,
    bech32Prefix: 'persistence',
    coinGeckoId: 'persistence',
  },
  [Networks.Axelar]: {
    network: Networks.Axelar,
    chainId: 'axelar-dojo-1',
    name: 'Axelar',
    denom: CosmosGasDenom.AXL,
    minimalDenom: CosmosGasDenom.uaxl,
    decimals: 6,
    bech32Prefix: 'axelar',
    coinGeckoId: 'axelar',
  },
  [Networks.Onomy]: {
    network: Networks.Onomy,
    chainId: 'onomy-mainnet-1',
    name: 'Onomy',
    denom: CosmosGasDenom.NOM,
    minimalDenom: CosmosGasDenom.anom,
    decimals: 6,
    bech32Prefix: 'onomy',
    coinGeckoId: 'onomy-protocol',
  },
  [Networks.Quicksilver]: {
    network: Networks.Quicksilver,
    chainId: 'quicksilver-2',
    name: 'Quicksilver',
    denom: CosmosGasDenom.QCK,
    minimalDenom: CosmosGasDenom.uqck,
    decimals: 6,
    bech32Prefix: 'quick',
    coinGeckoId: 'quicksilver',
  },
};
