import { CosmosGasDenom, CosmosNetworks, Networks } from '../enums';
import { CosmosChainConfig } from '../interfaces';

export const cosmosChainConfig: {
  [x in CosmosNetworks]: CosmosChainConfig;
} = {
  [Networks.Akash]: {
    network: Networks.Akash,
    chainId: 'akashnet-2',
    name: 'Akash',
    denom: CosmosGasDenom.AKT,
    minimalDenom: CosmosGasDenom.uakt,
    decimals: 6,
    bech32Prefix: 'akash',
    coinGeckoId: 'akash-network',
  },
  [Networks.Cosmos]: {
    network: Networks.Cosmos,
    chainId: 'cosmoshub-4',
    name: 'Cosmos',
    denom: CosmosGasDenom.ATOM,
    minimalDenom: CosmosGasDenom.uatom,
    decimals: 6,
    bech32Prefix: 'cosmos',
    coinGeckoId: 'cosmos',
  },
  [Networks.Kava]: {
    network: Networks.Kava,
    chainId: 'kava-9',
    name: 'Kava',
    denom: CosmosGasDenom.KAVA,
    minimalDenom: CosmosGasDenom.ukava,
    decimals: 6,
    bech32Prefix: 'kava',
    coinGeckoId: 'kava',
  },
  [Networks.Osmosis]: {
    network: Networks.Osmosis,
    chainId: 'osmosis-1',
    name: 'Osmosis',
    denom: CosmosGasDenom.OSMO,
    minimalDenom: CosmosGasDenom.uosmo,
    decimals: 6,
    bech32Prefix: 'osmo',
    coinGeckoId: 'osmosis',
  },
  [Networks.Juno]: {
    network: Networks.Juno,
    chainId: 'juno-1',
    name: 'Juno',
    denom: CosmosGasDenom.JUNO,
    minimalDenom: CosmosGasDenom.ujuno,
    decimals: 6,
    bech32Prefix: 'juno',
    coinGeckoId: 'juno-network',
  },
  [Networks.Stargaze]: {
    network: Networks.Stargaze,
    chainId: 'stargaze-1',
    name: 'Stargaze',
    denom: CosmosGasDenom.STARS,
    minimalDenom: CosmosGasDenom.ustars,
    decimals: 6,
    bech32Prefix: 'stars',
    coinGeckoId: 'stargaze',
  },
  [Networks.Persistence]: {
    network: Networks.Persistence,
    chainId: 'core-1',
    name: 'Persistence',
    denom: CosmosGasDenom.XPRT,
    minimalDenom: CosmosGasDenom.uxprt,
    decimals: 6,
    bech32Prefix: 'persistence',
    coinGeckoId: 'persistence',
  },
  [Networks.Axelar]: {
    network: Networks.Axelar,
    chainId: 'axelar-dojo-1',
    name: 'Axelar',
    denom: CosmosGasDenom.AXL,
    minimalDenom: CosmosGasDenom.uaxl,
    decimals: 6,
    bech32Prefix: 'axelar',
    coinGeckoId: 'axelar',
  },
  [Networks.Onomy]: {
    network: Networks.Onomy,
    chainId: 'onomy-mainnet-1',
    name: 'Onomy',
    denom: CosmosGasDenom.NOM,
    minimalDenom: CosmosGasDenom.anom,
    decimals: 6,
    bech32Prefix: 'onomy',
    coinGeckoId: 'onomy-protocol',
  },
  [Networks.Quicksilver]: {
    network: Networks.Quicksilver,
    chainId: 'quicksilver-2',
    name: 'Quicksilver',
    denom: CosmosGasDenom.QCK,
    minimalDenom: CosmosGasDenom.uqck,
    decimals: 6,
    bech32Prefix: 'quick',
    coinGeckoId: 'quicksilver',
  },
  [Networks.Agoric]: {
    network: Networks.Agoric,
    chainId: 'agoric-3',
    name: 'Agoric',
    denom: CosmosGasDenom.BLD,
    minimalDenom: CosmosGasDenom.ubld,
    decimals: 6,
    bech32Prefix: 'agoric',
    coinGeckoId: 'agoric',
  },
  [Networks.BandProtocol]: {
    network: Networks.BandProtocol,
    chainId: 'laozi-mainnet',
    name: 'Band Protocol',
    denom: CosmosGasDenom.BAND,
    minimalDenom: CosmosGasDenom.uband,
    decimals: 6,
    bech32Prefix: 'band',
    coinGeckoId: 'band-protocol',
  },
  [Networks.Bitsong]: {
    network: Networks.Bitsong,
    chainId: 'bitsong-2b',
    name: 'BitSong',
    denom: CosmosGasDenom.BTSG,
    minimalDenom: CosmosGasDenom.ubtsg,
    decimals: 6,
    bech32Prefix: 'bitsong',
    coinGeckoId: 'bitsong',
  },
  [Networks.Canto]: {
    network: Networks.Canto,
    chainId: 'canto_7700-1',
    name: 'Canto',
    denom: CosmosGasDenom.CANTO,
    minimalDenom: CosmosGasDenom.acanto,
    decimals: 18,
    bech32Prefix: 'canto',
    coinGeckoId: 'canto',
  },
  [Networks.Chihuahua]: {
    network: Networks.Chihuahua,
    chainId: 'chihuahua-1',
    name: 'Chihuahua',
    denom: CosmosGasDenom.HUAHUA,
    minimalDenom: CosmosGasDenom.uhuahua,
    decimals: 6,
    bech32Prefix: 'chihuahua',
    coinGeckoId: 'chihuahua-chain',
  },
  [Networks.Comdex]: {
    network: Networks.Comdex,
    chainId: 'comdex-1',
    name: 'Comdex',
    denom: CosmosGasDenom.CMDX,
    minimalDenom: CosmosGasDenom.ucmdx,
    decimals: 6,
    bech32Prefix: 'comdex',
    coinGeckoId: 'comdex',
  },
  [Networks.Crescent]: {
    network: Networks.Crescent,
    chainId: 'crescent-1',
    name: 'Crescent',
    denom: CosmosGasDenom.CRE,
    minimalDenom: CosmosGasDenom.ucre,
    decimals: 6,
    bech32Prefix: 'cre',
    coinGeckoId: 'crescent-network',
  },
  [Networks.Cronos]: {
    network: Networks.Cronos,
    chainId: 'cronosmainnet_25-1',
    name: 'Cronos',
    denom: CosmosGasDenom.CRO,
    minimalDenom: CosmosGasDenom.basecro,
    decimals: 18,
    bech32Prefix: 'crc',
    coinGeckoId: 'cronos',
  },
  [Networks.Cudos]: {
    network: Networks.Cudos,
    chainId: 'cudos-1',
    name: 'Cudos',
    denom: CosmosGasDenom.CUDOS,
    minimalDenom: CosmosGasDenom.acudos,
    decimals: 18,
    bech32Prefix: 'cudos',
    coinGeckoId: 'cudos',
  },
  [Networks.Evmos]: {
    network: Networks.Evmos,
    chainId: 'evmos_9001-2',
    name: 'Evmos',
    denom: CosmosGasDenom.EVMOS,
    minimalDenom: CosmosGasDenom.aevmos,
    decimals: 18,
    bech32Prefix: 'evmos',
    coinGeckoId: 'evmos',
  },
  [Networks.FetchAi]: {
    network: Networks.FetchAi,
    chainId: 'fetchhub-4',
    name: 'Fetch.ai',
    denom: CosmosGasDenom.FET,
    minimalDenom: CosmosGasDenom.afet,
    decimals: 18,
    bech32Prefix: 'fetch',
    coinGeckoId: 'fetch-ai',
  },
  [Networks.GravityBridge]: {
    network: Networks.GravityBridge,
    chainId: 'gravity-bridge-3',
    name: 'Gravity Bridge',
    denom: CosmosGasDenom.GRAVITON,
    minimalDenom: CosmosGasDenom.ugraviton,
    decimals: 6,
    bech32Prefix: 'gravity',
    coinGeckoId: 'graviton',
  },
  [Networks.Injective]: {
    network: Networks.Injective,
    chainId: 'injective-1',
    name: 'Injective',
    denom: CosmosGasDenom.INJ,
    minimalDenom: CosmosGasDenom.inj,
    decimals: 18,
    bech32Prefix: 'inj',
    coinGeckoId: 'injective',
  },
  [Networks.IRISnet]: {
    network: Networks.IRISnet,
    chainId: 'irishub-1',
    name: 'IRISnet',
    denom: CosmosGasDenom.IRIS,
    minimalDenom: CosmosGasDenom.uiris,
    decimals: 6,
    bech32Prefix: 'iaa',
    coinGeckoId: 'irisnet',
  },
  [Networks.KiNetwork]: {
    network: Networks.KiNetwork,
    chainId: 'kichain-2',
    name: 'Ki',
    denom: CosmosGasDenom.XKI,
    minimalDenom: CosmosGasDenom.uxki,
    decimals: 6,
    bech32Prefix: 'ki',
    coinGeckoId: 'ki',
  },
  [Networks.MarsProtocol]: {
    network: Networks.MarsProtocol,
    chainId: 'mars-1',
    name: 'Mars Hub',
    denom: CosmosGasDenom.MARS,
    minimalDenom: CosmosGasDenom.umars,
    decimals: 6,
    bech32Prefix: 'mars',
    coinGeckoId: 'mars-protocol',
  },
  [Networks.NYM]: {
    network: Networks.NYM,
    chainId: 'nyx',
    name: 'Nym',
    denom: CosmosGasDenom.NYM,
    minimalDenom: CosmosGasDenom.unym,
    decimals: 6,
    bech32Prefix: 'n',
    coinGeckoId: 'nym',
  },
  [Networks.OKExChain]: {
    network: Networks.OKExChain,
    chainId: 'exchain-66',
    name: 'OKExChain',
    denom: CosmosGasDenom.okt,
    minimalDenom: CosmosGasDenom.aokt,
    decimals: 18,
    bech32Prefix: 'ex',
    coinGeckoId: 'oec-token',
  },
  [Networks.Regen]: {
    network: Networks.Regen,
    chainId: 'regen-1',
    name: 'Regen',
    denom: CosmosGasDenom.REGEN,
    minimalDenom: CosmosGasDenom.uregen,
    decimals: 6,
    bech32Prefix: 'regen',
    coinGeckoId: 'regen',
  },
  [Networks.Secret]: {
    network: Networks.Secret,
    chainId: 'secret-4',
    name: 'Secret Network',
    denom: CosmosGasDenom.SCRT,
    minimalDenom: CosmosGasDenom.uscrt,
    decimals: 6,
    bech32Prefix: 'secret',
    coinGeckoId: 'secret',
  },
  [Networks.Sentinel]: {
    network: Networks.Sentinel,
    chainId: 'sentinelhub-2',
    name: 'Sentinel',
    denom: CosmosGasDenom.DVPN,
    minimalDenom: CosmosGasDenom.udvpn,
    decimals: 6,
    bech32Prefix: 'sent',
    coinGeckoId: 'sentinel',
  },
  [Networks.Sommelier]: {
    network: Networks.Sommelier,
    chainId: 'sommelier-3',
    name: 'Sommelier',
    denom: CosmosGasDenom.SOMM,
    minimalDenom: CosmosGasDenom.usomm,
    decimals: 6,
    bech32Prefix: 'somm',
    coinGeckoId: 'sommelier',
  },
  [Networks.StaFi]: {
    network: Networks.StaFi,
    chainId: 'stafihub-1',
    name: 'StaFi Hub',
    denom: CosmosGasDenom.FIS,
    minimalDenom: CosmosGasDenom.ufis,
    decimals: 6,
    bech32Prefix: 'stafi',
    coinGeckoId: 'stafi',
  },
  [Networks.Stride]: {
    network: Networks.Stride,
    chainId: 'stride-1',
    name: 'Stride',
    denom: CosmosGasDenom.STRD,
    minimalDenom: CosmosGasDenom.ustrd,
    decimals: 6,
    bech32Prefix: 'stride',
    coinGeckoId: 'stride',
  },
  [Networks.Teritori]: {
    network: Networks.Teritori,
    chainId: 'teritori-1',
    name: 'Teritori',
    denom: CosmosGasDenom.TORI,
    minimalDenom: CosmosGasDenom.utori,
    decimals: 6,
    bech32Prefix: 'tori',
    coinGeckoId: 'teritori',
  },
  [Networks.TGrade]: {
    network: Networks.TGrade,
    chainId: 'tgrade-mainnet-1',
    name: 'Tgrade',
    denom: CosmosGasDenom.TGD,
    minimalDenom: CosmosGasDenom.utgd,
    decimals: 6,
    bech32Prefix: 'tgrade',
    coinGeckoId: 'tgrade',
  },
  [Networks.Umee]: {
    network: Networks.Umee,
    chainId: 'umee-1',
    name: 'Umee',
    denom: CosmosGasDenom.UMEE,
    minimalDenom: CosmosGasDenom.uumee,
    decimals: 6,
    bech32Prefix: 'umee',
    coinGeckoId: 'umee',
  },
};
