import { Networks } from '../enums';

export const NetworkToCoinGeckoPlatformId: { [x in Networks]?: string } = {
  [Networks.Ethereum]: 'ethereum',
  [Networks.Cosmos]: 'cosmos',
  [Networks.Solana]: 'solana',
  [Networks.Kava]: 'kava',
  [Networks.Celo]: 'celo',
  [Networks.Osmosis]: 'osmosis',
  [Networks.Optimism]: 'optimistic-ethereum',
  [Networks.AvalancheC]: 'avalanche',
  [Networks.Fantom]: 'fantom',
  [Networks.Polygon]: 'polygon-pos',
  [Networks.Binance]: 'binance-smart-chain',
  [Networks.Harmony]: 'harmony-shard-0',
  [Networks.Arbitrum]: 'arbitrum-one',
  [Networks.Tezos]: 'tezos',
  [Networks.Stargaze]: 'stargaze',
  [Networks.Juno]: 'juno-network',
};

export const ChainIds: { [x in Networks]?: string } = {
  [Networks.Arbitrum]: '42161',
  [Networks.AvalancheC]: '43114',
  [Networks.Binance]: '56',
  [Networks.Celo]: '42220',
  [Networks.Ethereum]: '1',
  [Networks.EthereumGoerli]: '5',
  [Networks.Fantom]: '250',
  [Networks.Gnosis]: '100',
  [Networks.Near]: 'near',
  [Networks.Moonriver]: '1285',
  [Networks.Harmony]: '1666600000',
  [Networks.OKC]: '66',
  [Networks.Optimism]: '10',
  [Networks.Polygon]: '137',
  [Networks.Akash]: 'akashnet-2',
  [Networks.zkSync]: '324',
  [Networks.Solana]: '4sGjMW1sUnHzSxGspuhpqLDx6wiyjNtZ',
  [Networks.Cosmos]: 'cosmoshub-4',
  [Networks.Kava]: 'kava-9',
  [Networks.Juno]: 'juno-1',
  [Networks.Persistence]: 'core-1',
  [Networks.Stargaze]: 'stargaze-1',
  [Networks.Osmosis]: 'osmosis-1',
  [Networks.Tezos]: 'NetXdQprcVkpaWU',
};
