/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * StakeKit
 * StakeKit API documentation
 * OpenAPI spec version: 1.0
 */
import type { AddressesDto } from './addressesDto';
import type { ActionArgumentsDto } from './actionArgumentsDto';

export interface ActionRequestDto {
  integrationId: string;
  addresses: AddressesDto;
  args: ActionArgumentsDto;
}
