/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * StakeKit
 * StakeKit API documentation
 * OpenAPI spec version: 1.0
 */
import type { ActionStatus } from './actionStatus';
import type { ActionTypes } from './actionTypes';
import type { TransactionDto } from './transactionDto';

export interface ActionDto {
  id: string;
  status: ActionStatus;
  type: ActionTypes;
  currentStepIndex: number;
  amount: string | null;
  tokenId: string | null;
  validatorAddress: string | null;
  transactions: TransactionDto[];
}
