/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * StakeKit
 * StakeKit API documentation
 * OpenAPI spec version: 1.0
 */
import type { Networks } from './networks';
import type { AddressWithTokenDtoAdditionalAddresses } from './addressWithTokenDtoAdditionalAddresses';

export interface AddressWithTokenDto {
  address: string;
  network: Networks;
  additionalAddresses?: AddressWithTokenDtoAdditionalAddresses;
  tokenAddress?: string;
}
