/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * StakeKit
 * StakeKit API documentation
 * OpenAPI spec version: 1.0
 */
import type { CosmosAdditionalAddressesDto } from './cosmosAdditionalAddressesDto';
import type { BinanceAdditionalAddressesDto } from './binanceAdditionalAddressesDto';
import type { SolanaAdditionalAddressesDto } from './solanaAdditionalAddressesDto';
import type { TezosAdditionalAddressesDto } from './tezosAdditionalAddressesDto';

export type AddressesDtoAdditionalAddresses =
  | CosmosAdditionalAddressesDto
  | BinanceAdditionalAddressesDto
  | SolanaAdditionalAddressesDto
  | TezosAdditionalAddressesDto;
