/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * StakeKit
 * StakeKit API documentation
 * OpenAPI spec version: 1.0
 */
import type { RequiredArgumentWithNetworkDto } from './requiredArgumentWithNetworkDto';
import type { BinanceAdditionalAddressesStakeArgumentOptionsDto } from './binanceAdditionalAddressesStakeArgumentOptionsDto';

export interface AddressArgumentsDto {
  address?: RequiredArgumentWithNetworkDto;
  additionalAddresses?: BinanceAdditionalAddressesStakeArgumentOptionsDto[];
}
