/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * StakeKit
 * StakeKit API documentation
 * OpenAPI spec version: 1.0
 */
import type { RequiredArgumentDto } from './requiredArgumentDto';

export interface ApeNativeArgumentOptionsDto {
  baycId?: RequiredArgumentDto;
  maycId?: RequiredArgumentDto;
  bakcId?: RequiredArgumentDto;
}
