/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * StakeKit
 * StakeKit API documentation
 * OpenAPI spec version: 1.0
 */
import type { AmountArgumentOptionsDto } from './amountArgumentOptionsDto';
import type { DurationArgumentOptionsDto } from './durationArgumentOptionsDto';
import type { RequiredArgumentDto } from './requiredArgumentDto';
import type { ApeNativeArgumentOptionsDto } from './apeNativeArgumentOptionsDto';

export interface ArgumentOptionsDto {
  amount?: AmountArgumentOptionsDto;
  duration?: DurationArgumentOptionsDto;
  validatorAddress?: RequiredArgumentDto;
  nfts?: ApeNativeArgumentOptionsDto[];
}
