/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * StakeKit
 * StakeKit API documentation
 * OpenAPI spec version: 1.0
 */

export interface AuthUpdateDto {
  name: string;
  surname: string;
  password: string;
  oldPassword: string | null;
}
