/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * StakeKit
 * StakeKit API documentation
 * OpenAPI spec version: 1.0
 */
import type { UserDto } from './userDto';

export interface AuthEmailLoginResponseDto {
  token: string;
  user: UserDto;
}
