/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * StakeKit
 * StakeKit API documentation
 * OpenAPI spec version: 1.0
 */

export type BalanceTypes = (typeof BalanceTypes)[keyof typeof BalanceTypes];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BalanceTypes = {
  available: 'available',
  staked: 'staked',
  unstaking: 'unstaking',
  unstaked: 'unstaked',
  preparing: 'preparing',
  rewards: 'rewards',
  locked: 'locked',
} as const;
