/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * StakeKit
 * StakeKit API documentation
 * OpenAPI spec version: 1.0
 */
import type { CreateTeamDtoContactDetails } from './createTeamDtoContactDetails';
import type { CreateTeamDtoUser } from './createTeamDtoUser';

export interface CreateTeamDto {
  contactDetails: CreateTeamDtoContactDetails;
  name: string;
  user: CreateTeamDtoUser;
}
