/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * StakeKit
 * StakeKit API documentation
 * OpenAPI spec version: 1.0
 */
import type { CreateWebhookSubscriptionDtoEvent } from './createWebhookSubscriptionDtoEvent';

export interface CreateWebhookSubscriptionDto {
  callback: string;
  events: CreateWebhookSubscriptionDtoEvent[];
}
