/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * StakeKit
 * StakeKit API documentation
 * OpenAPI spec version: 1.0
 */

export interface CreateMasterBannedRegionDto {
  country: string;
  isMandatory: boolean;
  region?: string;
  tags: string[];
}
