/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * StakeKit
 * StakeKit API documentation
 * OpenAPI spec version: 1.0
 */
import type { Networks } from './networks';

export interface CustomUri {
  id: string;
  createdAt: string;
  updatedAt: string;
  network: Networks;
  rpcUri: string;
  projectId: string;
}
