/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * StakeKit
 * StakeKit API documentation
 * OpenAPI spec version: 1.0
 */
import type { EvmEIP1559GasArgsDtoType } from './evmEIP1559GasArgsDtoType';

export interface EvmEIP1559GasArgsDto {
  type: EvmEIP1559GasArgsDtoType;
  maxFeePerGas: string;
  maxPriorityFeePerGas: string;
}
