/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * StakeKit
 * StakeKit API documentation
 * OpenAPI spec version: 1.0
 */

export type EvmEIP1559GasArgsDtoType =
  (typeof EvmEIP1559GasArgsDtoType)[keyof typeof EvmEIP1559GasArgsDtoType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EvmEIP1559GasArgsDtoType = {
  NUMBER_2: 2,
} as const;
