/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * StakeKit
 * StakeKit API documentation
 * OpenAPI spec version: 1.0
 */

export type EvmLegacyGasArgsDtoType =
  (typeof EvmLegacyGasArgsDtoType)[keyof typeof EvmLegacyGasArgsDtoType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EvmLegacyGasArgsDtoType = {
  NUMBER_0: 0,
} as const;
