export type EvmNetworks = (typeof EvmNetworks)[keyof typeof EvmNetworks];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EvmNetworks = {
  ethereum: 'ethereum',
  'ethereum-goerli': 'ethereum-goerli',
  'ethereum-holesky': 'ethereum-holesky',
  'ethereum-sepolia': 'ethereum-sepolia',
  'ethereum-hoodi': 'ethereum-hoodi',
  arbitrum: 'arbitrum',
  base: 'base',
  'base-sepolia': 'base-sepolia',
  gnosis: 'gnosis',
  optimism: 'optimism',
  polygon: 'polygon',
  'polygon-amoy': 'polygon-amoy',
  starknet: 'starknet',
  zksync: 'zksync',
  linea: 'linea',
  unichain: 'unichain',
  'monad-testnet': 'monad-testnet',
  monad: 'monad',
  'avalanche-c': 'avalanche-c',
  'avalanche-c-atomic': 'avalanche-c-atomic',
  'avalanche-p': 'avalanche-p',
  binance: 'binance',
  celo: 'celo',
  fantom: 'fantom',
  harmony: 'harmony',
  moonriver: 'moonriver',
  okc: 'okc',
  viction: 'viction',
  core: 'core',
  sonic: 'sonic',
  plasma: 'plasma',
  katana: 'katana',
  hyperevm: 'hyperevm',
} as const;
