/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * StakeKit
 * StakeKit API documentation
 * OpenAPI spec version: 1.0
 */

export type GasMode = (typeof GasMode)[keyof typeof GasMode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GasMode = {
  slow: 'slow',
  average: 'average',
  fast: 'fast',
  custom: 'custom',
} as const;
