/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * StakeKit
 * StakeKit API documentation
 * OpenAPI spec version: 1.0
 */
import type { CosmosGasArgsDto } from './cosmosGasArgsDto';
import type { EvmEIP1559GasArgsDto } from './evmEIP1559GasArgsDto';
import type { EvmLegacyGasArgsDto } from './evmLegacyGasArgsDto';

/**
 * Custom gas properties to request transaction construction with. Can include properties like `gasPrice`, `maxGasPerFee`, etc for EVM chains.
 */
export type GasModeValueDtoGasArgs =
  | CosmosGasArgsDto
  | EvmEIP1559GasArgsDto
  | EvmLegacyGasArgsDto;
