/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * StakeKit
 * StakeKit API documentation
 * OpenAPI spec version: 1.0
 */
import type { GasModeValueDto } from './gasModeValueDto';

export interface GasModesDto {
  /** The denomination of the token gas is quoted in */
  denom: string;
  values: GasModeValueDto[];
}
