/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * StakeKit
 * StakeKit API documentation
 * OpenAPI spec version: 1.0
 */
import type { GasMode } from './gasMode';
import type { GasModeValueDtoGasArgs } from './gasModeValueDtoGasArgs';

export interface GasModeValueDto {
  name: GasMode;
  value: string;
  /** Custom gas properties to request transaction construction with. Can include properties like `gasPrice`, `maxGasPerFee`, etc for EVM chains. */
  gasArgs: GasModeValueDtoGasArgs;
}
