/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * StakeKit
 * StakeKit API documentation
 * OpenAPI spec version: 1.0
 */
import type { GeolocationErrorRegionCode } from './geolocationErrorRegionCode';
import type { GeolocationErrorTagsItem } from './geolocationErrorTagsItem';
import type { GeolocationErrorType } from './geolocationErrorType';

export interface GeolocationError {
  countryCode: string;
  regionCode?: GeolocationErrorRegionCode;
  tags?: GeolocationErrorTagsItem[];
  code: number;
  message: string;
  type: GeolocationErrorType;
}
