/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * StakeKit
 * StakeKit API documentation
 * OpenAPI spec version: 1.0
 */

export type GeolocationErrorType =
  (typeof GeolocationErrorType)[keyof typeof GeolocationErrorType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GeolocationErrorType = {
  GEO_LOCATION: 'GEO_LOCATION',
} as const;
