/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * StakeKit
 * StakeKit API documentation
 * OpenAPI spec version: 1.0
 */
import type { InfinityPaginatedDtoData } from './infinityPaginatedDtoData';

export interface InfinityPaginatedDto {
  data: InfinityPaginatedDtoData;
  hasNextPage: boolean;
  limit: number;
  page: number;
}
