/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * StakeKit
 * StakeKit API documentation
 * OpenAPI spec version: 1.0
 */

export type KeyCategory = (typeof KeyCategory)[keyof typeof KeyCategory];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const KeyCategory = {
  pro: 'pro',
  standard: 'standard',
  trial: 'trial',
} as const;
