/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * StakeKit
 * StakeKit API documentation
 * OpenAPI spec version: 1.0
 */
import type { StakeSessionTypes } from './stakeSessionTypes';
import type { StakeArgumentOptionsDto } from './stakeArgumentOptionsDto';

export interface PendingActionDto {
  /** The pending action type */
  type: StakeSessionTypes;
  /** A server generated passthrough that must passed back when pulling the transactions for a given pending action */
  passthrough: string;
  /** Any user chosen options for the pending action. Possible options can be  */
  args?: StakeArgumentOptionsDto;
}
