/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * StakeKit
 * StakeKit API documentation
 * OpenAPI spec version: 1.0
 */
import type { StakeSessionTypes } from './stakeSessionTypes';
import type { PendingActionArgumentsDto } from './pendingActionArgumentsDto';

export interface PendingActionRequestDto {
  type: StakeSessionTypes;
  integrationId: string;
  /** The corresponding passthrough for the pending action to be run, returned in the balances endpoint */
  passthrough: string;
  args?: PendingActionArgumentsDto;
}
