/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * StakeKit
 * StakeKit API documentation
 * OpenAPI spec version: 1.0
 */
import type { TokenDto } from './tokenDto';

export interface PriceRequestDto {
  currency: string;
  tokenList: TokenDto[];
}
