/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * StakeKit
 * StakeKit API documentation
 * OpenAPI spec version: 1.0
 */

export interface Project {
  id: string;
  createdAt: string;
  updatedAt: string;
  autoComplaintBansEnabled: boolean;
  deletedAt: string | null;
  description: string | null;
  name: string;
  teamId: string;
}
