/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * StakeKit
 * StakeKit API documentation
 * OpenAPI spec version: 1.0
 */
import type { ProjectDeletedAt } from './projectDeletedAt';

export interface Project {
  id: string;
  createdAt: string;
  updatedAt: string;
  deletedAt: ProjectDeletedAt;
  name: string;
  teamId: string;
}
