export type RequiredArgumentWithNetworkDtoNetwork =
  (typeof RequiredArgumentWithNetworkDtoNetwork)[keyof typeof RequiredArgumentWithNetworkDtoNetwork];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RequiredArgumentWithNetworkDtoNetwork = {
  'avalanche-c': 'avalanche-c',
  'avalanche-c-atomic': 'avalanche-c-atomic',
  'avalanche-p': 'avalanche-p',
  arbitrum: 'arbitrum',
  binance: 'binance',
  celo: 'celo',
  ethereum: 'ethereum',
  'ethereum-goerli': 'ethereum-goerli',
  fantom: 'fantom',
  harmony: 'harmony',
  optimism: 'optimism',
  polygon: 'polygon',
  akash: 'akash',
  cosmos: 'cosmos',
  juno: 'juno',
  kava: 'kava',
  osmosis: 'osmosis',
  stargaze: 'stargaze',
  onomy: 'onomy',
  persistence: 'persistence',
  axelar: 'axelar',
  quicksilver: 'quicksilver',
  agoric: 'agoric',
  'band-protocol': 'band-protocol',
  bitsong: 'bitsong',
  canto: 'canto',
  chihuahua: 'chihuahua',
  comdex: 'comdex',
  crescent: 'crescent',
  cronos: 'cronos',
  cudos: 'cudos',
  evmos: 'evmos',
  'fetch-ai': 'fetch-ai',
  'gravity-bridge': 'gravity-bridge',
  injective: 'injective',
  irisnet: 'irisnet',
  'ki-network': 'ki-network',
  'mars-protocol': 'mars-protocol',
  nym: 'nym',
  'okex-chain': 'okex-chain',
  regen: 'regen',
  secret: 'secret',
  sentinel: 'sentinel',
  sommelier: 'sommelier',
  stafi: 'stafi',
  stride: 'stride',
  teritori: 'teritori',
  tgrade: 'tgrade',
  umee: 'umee',
  coreum: 'coreum',
  desmos: 'desmos',
  binancebeacon: 'binancebeacon',
  near: 'near',
  solana: 'solana',
  tezos: 'tezos',
  tron: 'tron',
} as const;
