/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * StakeKit
 * StakeKit API documentation
 * OpenAPI spec version: 1.0
 */

export type RequiredArgumentWithNetworkDtoNetwork =
  (typeof RequiredArgumentWithNetworkDtoNetwork)[keyof typeof RequiredArgumentWithNetworkDtoNetwork];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RequiredArgumentWithNetworkDtoNetwork = {
  'avalanche-c': 'avalanche-c',
  'avalanche-c-atomic': 'avalanche-c-atomic',
  'avalanche-p': 'avalanche-p',
  arbitrum: 'arbitrum',
  binance: 'binance',
  celo: 'celo',
  ethereum: 'ethereum',
  'ethereum-goerli': 'ethereum-goerli',
  fantom: 'fantom',
  harmony: 'harmony',
  optimism: 'optimism',
  polygon: 'polygon',
  akash: 'akash',
  cosmos: 'cosmos',
  juno: 'juno',
  kava: 'kava',
  osmosis: 'osmosis',
  stargaze: 'stargaze',
  onomy: 'onomy',
  persistence: 'persistence',
  axelar: 'axelar',
  quicksilver: 'quicksilver',
  binancebeacon: 'binancebeacon',
  near: 'near',
  solana: 'solana',
  tezos: 'tezos',
} as const;
