/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * StakeKit
 * StakeKit API documentation
 * OpenAPI spec version: 1.0
 */

export type RewardClaiming =
  (typeof RewardClaiming)[keyof typeof RewardClaiming];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RewardClaiming = {
  auto: 'auto',
  manual: 'manual',
} as const;
