/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * StakeKit
 * StakeKit API documentation
 * OpenAPI spec version: 1.0
 */
import type { StakeStatus } from './stakeStatus';
import type { StakeSessionTypes } from './stakeSessionTypes';
import type { TransactionDto } from './transactionDto';

export interface StakeDto {
  id: string;
  status: StakeStatus;
  type: StakeSessionTypes;
  currentStepIndex: number;
  amount: string | null;
  tokenId: string | null;
  validatorAddress: string | null;
  transactions: TransactionDto[];
}
