/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * StakeKit
 * StakeKit API documentation
 * OpenAPI spec version: 1.0
 */
import type { StakeV2YieldOpportunitiesType } from './stakeV2YieldOpportunitiesType';
import type { StakeV2YieldOpportunitiesSortBy } from './stakeV2YieldOpportunitiesSortBy';
import type { StakeV2YieldOpportunitiesNetwork } from './stakeV2YieldOpportunitiesNetwork';

export type StakeV2YieldOpportunitiesParams = {
  type?: StakeV2YieldOpportunitiesType;
  sortBy?: StakeV2YieldOpportunitiesSortBy;
  page?: number;
  network?: StakeV2YieldOpportunitiesNetwork;
  limit?: number;
};
