/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * StakeKit
 * StakeKit API documentation
 * OpenAPI spec version: 1.0
 */
import type { ApeNativeArgumentsDto } from './apeNativeArgumentsDto';

export interface StakeArgumentsDto {
  amount: string;
  validatorAddress?: string;
  duration?: number;
  nfts?: ApeNativeArgumentsDto;
}
