/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * StakeKit
 * StakeKit API documentation
 * OpenAPI spec version: 1.0
 */
import type { AddressArgumentsDto } from './addressArgumentsDto';
import type { ArgumentOptionsDto } from './argumentOptionsDto';

export interface StakeArgumentOptionsDto {
  addresses?: AddressArgumentsDto;
  args?: ArgumentOptionsDto;
}
