/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * StakeKit
 * StakeKit API documentation
 * OpenAPI spec version: 1.0
 */

export type StakeV2YieldOpportunitiesType =
  (typeof StakeV2YieldOpportunitiesType)[keyof typeof StakeV2YieldOpportunitiesType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StakeV2YieldOpportunitiesType = {
  staking: 'staking',
  'liquid-staking': 'liquid-staking',
  lending: 'lending',
  vault: 'vault',
} as const;
