/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * StakeKit
 * StakeKit API documentation
 * OpenAPI spec version: 1.0
 */

export type StakeV2YieldOpportunitiesSortBy =
  (typeof StakeV2YieldOpportunitiesSortBy)[keyof typeof StakeV2YieldOpportunitiesSortBy];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StakeV2YieldOpportunitiesSortBy = {
  name: 'name',
  yieldType: 'yieldType',
} as const;
