/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * StakeKit
 * StakeKit API documentation
 * OpenAPI spec version: 1.0
 */
import type { InfinityPaginatedDto } from './infinityPaginatedDto';
import type { StakeV2GetMyYieldOpportunities200AllOf } from './stakeV2GetMyYieldOpportunities200AllOf';

export type StakeV2GetMyYieldOpportunities200 = InfinityPaginatedDto &
  StakeV2GetMyYieldOpportunities200AllOf;
