/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * StakeKit
 * StakeKit API documentation
 * OpenAPI spec version: 1.0
 */

export interface SubmitRequestDto {
  /** Signed transaction to be broadcast to the network */
  signedTransaction: string;
}
