/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * StakeKit
 * StakeKit API documentation
 * OpenAPI spec version: 1.0
 */
import type { UserDto } from './userDto';
import type { TeamDtoContactDetails } from './teamDtoContactDetails';

export interface TeamDto {
  id: string;
  activated: boolean;
  adminUser: UserDto;
  deletedAt: string | null;
  createdAt: string;
  contactDetails: TeamDtoContactDetails;
  name: string;
  serviceConditionsAcceptedAt: string | null;
}
