/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * StakeKit
 * StakeKit API documentation
 * OpenAPI spec version: 1.0
 */
import type { Networks } from './networks';

export interface TokenDto {
  name: string;
  network: Networks;
  symbol: string;
  decimals: number;
  address?: string;
  coinGeckoId?: string;
  logoURI?: string;
}
