/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * StakeKit
 * StakeKit API documentation
 * OpenAPI spec version: 1.0
 */
import type { TransactionStatus } from './transactionStatus';
import type { Networks } from './networks';
import type { TransactionStatusResponseDtoRaw } from './transactionStatusResponseDtoRaw';

export interface TransactionStatusResponseDto {
  status: TransactionStatus;
  url: string;
  blockNumber?: string;
  network: Networks;
  hash: string;
  raw: TransactionStatusResponseDtoRaw;
}
