/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * StakeKit
 * StakeKit API documentation
 * OpenAPI spec version: 1.0
 */

export type UpdatePayoutAddressDtoNetwork =
  (typeof UpdatePayoutAddressDtoNetwork)[keyof typeof UpdatePayoutAddressDtoNetwork];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdatePayoutAddressDtoNetwork = {
  'avalanche-c': 'avalanche-c',
  arbitrum: 'arbitrum',
  binance: 'binance',
  celo: 'celo',
  ethereum: 'ethereum',
  'ethereum-goerli': 'ethereum-goerli',
  fantom: 'fantom',
  harmony: 'harmony',
  optimism: 'optimism',
  polygon: 'polygon',
  akash: 'akash',
  cosmos: 'cosmos',
  juno: 'juno',
  kava: 'kava',
  osmosis: 'osmosis',
  stargaze: 'stargaze',
  binancebeacon: 'binancebeacon',
  near: 'near',
  solana: 'solana',
  tezos: 'tezos',
} as const;
