/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * StakeKit
 * StakeKit API documentation
 * OpenAPI spec version: 1.0
 */
import type { KeyCategory } from './keyCategory';

export interface UpdateTeamDto {
  activated?: boolean;
  serviceConditionsAccepted?: boolean;
  category?: KeyCategory;
  name?: string;
  providerFeePercentage?: number;
}
