/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * StakeKit
 * StakeKit API documentation
 * OpenAPI spec version: 1.0
 */

export interface ValidatorDto {
  address: string;
  name: string;
  image: string;
  website: string | null;
  apr: number | null;
  commission: number | null;
  stakedBalance: string | null;
  votingPower: number | null;
}
