import type { ValidatorAdminDtoApr } from './validatorAdminDtoApr';
import type { ValidatorAdminDtoAprOverride } from './validatorAdminDtoAprOverride';
import type { ValidatorAdminDtoCommission } from './validatorAdminDtoCommission';
import type { ValidatorAdminDtoCommissionOverride } from './validatorAdminDtoCommissionOverride';
import type { ValidatorAdminDtoEndDate } from './validatorAdminDtoEndDate';
import type { ValidatorAdminDtoImage } from './validatorAdminDtoImage';
import type { ValidatorAdminDtoImageOverride } from './validatorAdminDtoImageOverride';
import type { ValidatorAdminDtoLastFoundAt } from './validatorAdminDtoLastFoundAt';
import type { ValidatorAdminDtoMevCommission } from './validatorAdminDtoMevCommission';
import type { ValidatorAdminDtoMevCommissionOverride } from './validatorAdminDtoMevCommissionOverride';
import type { ValidatorAdminDtoMinimumStake } from './validatorAdminDtoMinimumStake';
import type { ValidatorAdminDtoName } from './validatorAdminDtoName';
import type { ValidatorAdminDtoNameOverride } from './validatorAdminDtoNameOverride';
import type { ValidatorAdminDtoNominatorCount } from './validatorAdminDtoNominatorCount';
import type { ValidatorProviderDto } from './validatorProviderDto';
import type { ValidatorAdminDtoProviderId } from './validatorAdminDtoProviderId';
import type { ValidatorAdminDtoRemainingPossibleStake } from './validatorAdminDtoRemainingPossibleStake';
import type { ValidatorAdminDtoRemainingSlots } from './validatorAdminDtoRemainingSlots';
import type { ValidatorAdminDtoStakedBalance } from './validatorAdminDtoStakedBalance';
import type { ValidatorStatusTypes } from './validatorStatusTypes';
import type { ValidatorAdminDtoSubnetId } from './validatorAdminDtoSubnetId';
import type { ValidatorAdminDtoVotingPower } from './validatorAdminDtoVotingPower';
import type { ValidatorAdminDtoWebsite } from './validatorAdminDtoWebsite';
import type { ValidatorAdminDtoWebsiteOverride } from './validatorAdminDtoWebsiteOverride';

export interface ValidatorAdminDto {
  address: string;
  apr?: ValidatorAdminDtoApr;
  aprOverride?: ValidatorAdminDtoAprOverride;
  commission?: ValidatorAdminDtoCommission;
  commissionOverride?: ValidatorAdminDtoCommissionOverride;
  createdAt: string;
  endDate?: ValidatorAdminDtoEndDate;
  id: string;
  image?: ValidatorAdminDtoImage;
  imageOverride?: ValidatorAdminDtoImageOverride;
  integrationId: string;
  lastFoundAt?: ValidatorAdminDtoLastFoundAt;
  mevCommission?: ValidatorAdminDtoMevCommission;
  mevCommissionOverride?: ValidatorAdminDtoMevCommissionOverride;
  minimumStake?: ValidatorAdminDtoMinimumStake;
  name?: ValidatorAdminDtoName;
  nameOverride?: ValidatorAdminDtoNameOverride;
  nominatorCount?: ValidatorAdminDtoNominatorCount;
  provider?: ValidatorProviderDto;
  providerId?: ValidatorAdminDtoProviderId;
  remainingPossibleStake?: ValidatorAdminDtoRemainingPossibleStake;
  remainingSlots?: ValidatorAdminDtoRemainingSlots;
  stakedBalance?: ValidatorAdminDtoStakedBalance;
  status: ValidatorStatusTypes;
  subnetId?: ValidatorAdminDtoSubnetId;
  updatedAt: string;
  votingPower?: ValidatorAdminDtoVotingPower;
  website?: ValidatorAdminDtoWebsite;
  websiteOverride?: ValidatorAdminDtoWebsiteOverride;
}
