/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * StakeKit
 * StakeKit API documentation
 * OpenAPI spec version: 1.0
 */
import type { WebhookSubscriptionEventDto } from './webhookSubscriptionEventDto';

export interface WebhookSubscriptionDto {
  id: string;
  callback: string;
  events: WebhookSubscriptionEventDto[];
}
