export type YieldV2YieldsProviderId =
  (typeof YieldV2YieldsProviderId)[keyof typeof YieldV2YieldsProviderId];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const YieldV2YieldsProviderId = {
  aave: 'aave',
  anchor: 'anchor',
  benqi: 'benqi',
  compound: 'compound',
  lido: 'lido',
  sushi: 'sushi',
  yearn: 'yearn',
  ape: 'ape',
  chainlink: 'chainlink',
  pendle: 'pendle',
  parax: 'parax',
  'rocket-pool': 'rocket-pool',
  stakewise: 'stakewise',
  etherfi: 'etherfi',
  'morpho-aave': 'morpho-aave',
  morpho: 'morpho',
  'morpho-compound': 'morpho-compound',
  angle: 'angle',
  kelpdao: 'kelpdao',
  figment: 'figment',
  kiln: 'kiln',
  P2P: 'P2P',
  everstake: 'everstake',
  eigenlayer: 'eigenlayer',
  luganodes: 'luganodes',
  renzo: 'renzo',
  infstones: 'infstones',
  ethena: 'ethena',
  upshift: 'upshift',
  fluid: 'fluid',
  'idle-finance': 'idle-finance',
  gearbox: 'gearbox',
  'chorus-one': 'chorus-one',
  stakekit: 'stakekit',
  spark: 'spark',
  sommelier: 'sommelier',
  venus: 'venus',
  mantle: 'mantle',
  'ton-whales': 'ton-whales',
  blend: 'blend',
  synthetix: 'synthetix',
  drift: 'drift',
  euler: 'euler',
  maple: 'maple',
  sky: 'sky',
  'yo-protocol': 'yo-protocol',
  meria: 'meria',
  stakin: 'stakin',
  globalstake: 'globalstake',
  simplystaking: 'simplystaking',
  coinbase: 'coinbase',
  'validation-cloud': 'validation-cloud',
  curve: 'curve',
} as const;
