/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * StakeKit
 * StakeKit API documentation
 * OpenAPI spec version: 1.0
 */

export type YieldYieldsSortBy =
  (typeof YieldYieldsSortBy)[keyof typeof YieldYieldsSortBy];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const YieldYieldsSortBy = {
  name: 'name',
  yieldType: 'yieldType',
} as const;
