/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * StakeKit
 * StakeKit API documentation
 * OpenAPI spec version: 1.0
 */
import type { AddressesDto } from './addressesDto';
import type { ValidatorAddressesDto } from './validatorAddressesDto';

export interface YieldBalanceWithIntegrationIdRequestDto {
  addresses: AddressesDto;
  args?: ValidatorAddressesDto;
  integrationId: string;
}
