export type YieldProviders =
  (typeof YieldProviders)[keyof typeof YieldProviders];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const YieldProviders = {
  aave: 'aave',
  anchor: 'anchor',
  benqi: 'benqi',
  compound: 'compound',
  lido: 'lido',
  sushi: 'sushi',
  yearn: 'yearn',
  ape: 'ape',
  chainlink: 'chainlink',
  pendle: 'pendle',
  parax: 'parax',
  'rocket-pool': 'rocket-pool',
  stakewise: 'stakewise',
  etherfi: 'etherfi',
  'morpho-aave': 'morpho-aave',
  'morpho-blue': 'morpho-blue',
  'morpho-compound': 'morpho-compound',
  angle: 'angle',
  kelpdao: 'kelpdao',
  figment: 'figment',
  kiln: 'kiln',
  P2P: 'P2P',
  everstake: 'everstake',
  eigenlayer: 'eigenlayer',
  luganodes: 'luganodes',
  renzo: 'renzo',
  infstones: 'infstones',
  ethena: 'ethena',
  fluid: 'fluid',
} as const;
