/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * StakeKit
 * StakeKit API documentation
 * OpenAPI spec version: 1.0
 */
import type { TokenDto } from './tokenDto';
import type { ActionArgumentResponseDto } from './actionArgumentResponseDto';
import type { YieldStatusResponseDto } from './yieldStatusResponseDto';
import type { YieldMetadataDto } from './yieldMetadataDto';
import type { ValidatorDto } from './validatorDto';

export interface YieldDto {
  /** The yield opportunity ID */
  id: string;
  token: TokenDto;
  args: ActionArgumentResponseDto;
  status: YieldStatusResponseDto;
  apy: number;
  metadata: YieldMetadataDto;
  validators: ValidatorDto[];
}
