/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * StakeKit
 * StakeKit API documentation
 * OpenAPI spec version: 1.0
 */
import type { InfinityPaginatedDto } from './infinityPaginatedDto';
import type { YieldYields200AllOf } from './yieldYields200AllOf';

export type YieldYields200 = InfinityPaginatedDto & YieldYields200AllOf;
