/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * StakeKit
 * StakeKit API documentation
 * OpenAPI spec version: 1.0
 */

export type YieldYieldsType =
  (typeof YieldYieldsType)[keyof typeof YieldYieldsType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const YieldYieldsType = {
  staking: 'staking',
  'liquid-staking': 'liquid-staking',
  lending: 'lending',
  vault: 'vault',
} as const;
