/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * StakeKit
 * StakeKit API documentation
 * OpenAPI spec version: 1.0
 */
import type { YieldType } from './yieldType';
import type { RewardSchedule } from './rewardSchedule';
import type { TimePeriodDto } from './timePeriodDto';
import type { RewardClaiming } from './rewardClaiming';
import type { TokenDto } from './tokenDto';
import type { YieldRevshareDto } from './yieldRevshareDto';
import type { YieldFeeDto } from './yieldFeeDto';

export interface YieldConfigDto {
  type: YieldType;
  rewardSchedule: RewardSchedule;
  cooldownPeriod: TimePeriodDto;
  warmupPeriod: TimePeriodDto;
  withdrawPeriod?: TimePeriodDto;
  rewardClaiming: RewardClaiming;
  rewardTokens?: TokenDto[];
  defaultValidator?: string;
  minimumStake?: number;
  supportsMultipleValidators?: boolean;
  revshare: YieldRevshareDto;
  fee: YieldFeeDto;
}
