/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * StakeKit
 * StakeKit API documentation
 * OpenAPI spec version: 1.0
 */
import type { InfinityPaginatedDto } from './infinityPaginatedDto';
import type { YieldGetMyYields200AllOf } from './yieldGetMyYields200AllOf';

export type YieldGetMyYields200 = InfinityPaginatedDto &
  YieldGetMyYields200AllOf;
